### ISSUE TITLE
When storing events with simple arrays of primitives - it generates a structure for MongoDB that is coupled to .NET

### ISSUE THREAD

**Issue by einari** [dolittle-extensions/Runtime.Events.MongoDB#23]
The event looks like the following in C#:

```csharp
    public class ThrottleChanged : IEvent
    {

        public ThrottleChanged(int[] engines, double target)
        {
            Engines = engines;
            Target = target;
        }

        public int[] Engines { get; }
        public double Target { get; }
    }
```

This gets translated to:

![image](https://user-images.githubusercontent.com/134365/46944126-8ff6d400-d071-11e8-9c38-c2c9c4f055ba.png)

We need to just store these as a simple primitive Array - a `BsonClassMap` might do the trick here.

**Comment by woksin** [comment]
I think that this is something we need to look at, the BsonClassMap thing. Maybe we should look at centralizing most of the pain points when working with Mongo in our MongoDB implementations, @einari, @smithmx

**Comment by einari** [comment]
Totally agree - we need to gather all things we've scattered across different projects and fix them in one place. It is super important that we don't bleed implementation details from .NET into the actual data being stored. It looks weird, plus standard tools won't help you even on doing queries.
